"""
Defines configuration constants for paths and directories used in the analytics module.
"""
from __future__ import annotations

from pathlib import Path

# Analytics will default to hiero-ledger org
ORG = "hiero-ledger"

"""
PROJECT_ROOT is the root directory of the project, calculated as three levels up from this file's location.
OUTPUTS_DIR is the main directory for all outputs generated by the analytics module, including data files and charts.
DATA_DIR is the subdirectory within OUTPUTS_DIR where all data files (e.g., CSVs, JSONs) will be stored.
CHARTS_DIR is the subdirectory within OUTPUTS_DIR where all generated charts (e.g., PNGs, SVGs) will be saved.
CACHE_DIR is the directory where cached data from GitHub API requests will be stored to avoid redundant requests.
"""
PROJECT_ROOT = Path(__file__).resolve().parents[3]
OUTPUTS_DIR = PROJECT_ROOT / "outputs"
DATA_DIR = OUTPUTS_DIR / "data"
CHARTS_DIR = OUTPUTS_DIR / "charts"
CACHE_DIR = Path(".cache/github")

def ensure_output_dirs() -> None:
    """
    Ensure the above directories exist.
    Should be called by runner scripts before writing files to ensure they can be saved to that location
    
    Args:
        None
    Returns:
        None
    """
    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    CHARTS_DIR.mkdir(parents=True, exist_ok=True)
    CACHE_DIR.mkdir(parents=True, exist_ok=True)